### ISSUE TITLE
Создать шаблоны для заявки

### ISSUE THREAD

**Issue by denisSurkov** [alexbagirov/uralsp-reg-site#20]
### Мотивация
Нам нужно выводить некоторые данные в списке всех заявок. К примеру, название команды, фио участников. 

Если бы каждая заявка состояла из определенных полей, то тут не было бы проблем. Но у нас формирование формы заявки динамическое (в плане от соревнования к соревнованию поля могут менятся, как гугл форма). Выходит, что единого формата отображения заявки нет.

Выводить все заполненные поля рядом с заявкой затратно по количеству запросов к бд. 

### Решение
При создании соревнования мы можем присвоить каждому полю кастомный человекочитаемый идшник (teamName, fio, school).

Если у каждого поля будет идишник, то админ может сформировать шаблоны.

Шаблоны формируются отдельно для каждого блока - для общих полей и шаблон для участника команды.

К примеру, у нас есть поля:

Общие
Название команды (teamName)
Город участников (city)

Участник
ФИО (fio)
Школа (school)

Тогда ниже могут быть такие шаблоны:

Шаблон для общих полей
{{ teamName }} из {{ city }}

Шаблон для участника
{{ fio }} ({{ school }})

Эти шаблоны нужно сохранить в Competition. Поля string CommonFieldsTemplate, string PersonalFieldsTemplate. 

Когда юзер создает заявку, нам нужно взять все данные и отредерить их по шаблонам. Положить в CompetitionApplication (string CommonData, string PersonalData). В PersonalData склеить все данные участников через какой-нибудь разделитель. 

#### Как раньше выглядели шаблоны
![telegram-cloud-photo-size-2-5278667566342060238-y](https://user-images.githubusercontent.com/34986204/144286599-536de826-f25b-4762-a196-f9c9510b97b1.jpg)

Для рендеринга шаблонов лучше использовать https://github.com/scriban/scriban

**Comment by artemijkurganov** [comment]
@denisSurkov 
> Эти шаблоны нужно сохранить в Competition. Поля string CommonFieldsTemplate, string PersonalFieldsTemplate.

Точно в `Competition`? Может лучше в `TemplateField`? 
Удобнее будет хранить "человекочитаемый айдишник" рядом с полем.

Если хранить в Competition`, как мы потом восстановим соответствие?

**Comment by denisSurkov** [comment]
> Удобнее будет хранить "человекочитаемый айдишник" рядом с полем.

Да, так и надо. Я говорил именно про шаблоны.

**Comment by artemijkurganov** [comment]
> Я говорил именно про шаблоны.

Ой, да, точно. 🤭

**Comment by artemijkurganov** [comment]
Задачи:

- [ ]  Создать кеширование отображений, чтобы при каждом просмотре заявок не ходить в базу данных
- [ ] Написать тесты
