### ISSUE TITLE
Сделать отображение типов полей на русском

### ISSUE THREAD

**Issue by denisSurkov** [alexbagirov/uralsp-reg-site#9]
Через атрибуты нужно сделать перевод для каждого типа из enum'a. 

**Важно**, чтобы значения из атрибутов брались один раз.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/34986204/142614379-2627fc04-8440-41d6-b834-edeb4d651674.png">

**Comment by artemijkurganov** [comment]
Сломалось после #15
